---
###############################################################################
# Prep
###############################################################################
# Create user if needed and determine UID/GID for potential remote filesystems.
# Stop services if they exist (MongoDB should always be shutdown for config
# changes).

- name: 'Prep | manage users'
  when: _mongodb_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ mongodb_role_user }}'
    users_role_group: '{{ mongodb_role_group }}'

- name: 'Prep | enumerate system user {{ _mongodb_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _mongodb_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _mongodb_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _mongodb_srv_user: '{{
        _mongodb_srv_user |
        combine({"_uid": _mongodb_srv_user_query.uid})
      }}'
    _mongodb_srv_group: '{{
        _mongodb_srv_group |
        combine({"_gid": _mongodb_srv_user_query.group})
      }}'

- name: 'Prep | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'mongod.service'
