---
###############################################################################
# Default
###############################################################################
# Default install configures default Debian MongoDB install.
#
# Tests:
# * service running.
# * /etc/mongod.conf is equivalent to Debian default.
# * Default options are set correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'virtualbox'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'root'
    options:
      append_platform_to_hostname: false
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        mongodb_srv_backup_enable: true
        mongodb_srv_user_data_manage_enable: true
platforms:
  - name: 'mongodb-debian-13-vm-default'
    box: 'inception-of-things/debian-trixie'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network  # network_name required.
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # services created one time.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
